apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-echo-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /echo
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-echo-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`localhost`) && PathPrefix(`/echo`)
      kind: Rule
      middlewares:
        - name: strip-echo-prefix
      services:
        - name: nginx-echo
          port: 80