apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-route-without-strip
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`localhost`) && PathPrefix(`/whoami-without-strip`)
      kind: Rule
      services:
        - name: whoami-without-strip
          port: 80